name: format
run-name: Formatting the files in the commit before merging.

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn install
      - name: Format the files
        run: yarn format:fix
      - name: Commit the changes
        run: |
          git config --local user.email "
